# Generated by Django 4.2.5 on 2023-10-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Big_inApp', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
