# Generated by Django 4.2.5 on 2023-12-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Big_inApp', '0006_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
