# Generated by Django 3.2.19 on 2023-12-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Big_inApp', '0008_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
